diction = { #type:ignore
    "Obair Dhian":{ #type:ignore
        "first":"Leagadh síos bunchloch an scéil sa chéad phictiúr. Lá dá raibh ag tús na séú bliana a bhí ann agus bhí na daltaí go léir ar ais ar scoil. Feicimid Máire ina suí in oifig an gairmthreoraí. Bhuail sí leis an ngairmthreoraí agus phléigh siad a roghanna don bhliain seo chugainn. Luaigh Máire go raibh suim aici sa cheimic sa Ghaillimh agus lorg sí eolas ón múinteoir. Mhínigh sé go raibh ceithre chéad pointe ag teastáil don chúrsa agus go mbeadh obair dhian ag teastáil.",
        "second":"Bogadh an scéal ar aghaidh sa dara phictiúr. An tráthnóna sin, bhuail Máire lena cara Síle agus shiúil siad abhaile le chéile.Labhair siad faoin lá agus faoi na ranganna a bhí acu. Feicimid buachaillí ag traenáil don chispheil sa chúlra. Thug Síle cuireadh do Mháire teacht chuig a teach do chupán tae, ach níor ghlac Máire leis an gcuireadh. Mhínigh sí go raibh a lán obair bhaile le déanamh aici.",
        "third":"Tá an pictiúr seo roinnte ina dhá leath. Lean an scéal ar aghaidh, agus níos déanaí an tráthnóna sin bhí Máire sa bhaile. Bhuail a fón póca agus d'fhreagair sí é. Ghlaoigh Seán uirthi agus thug sé cuireadh chuig an bpictiúrlann di. Dúirt sé léi go raibh scannán iontach sa phictiúrlann, ach arís eile dhiúltaigh Máire an cuireadh. Bhí aiste Béarla le scríobh aici an oíche sin.",
        "fourth":"Leantar leis an scéal sa chéad phictiúr eile. Feicimid Máire ina seomra leapa ag staidéar. Bhí sí ag obair go dian dícheallach agus bhí an iliomad leabhair timpeall uirthi. Bhí a tuismitheoirí sa chistin agus bhí siad ag caint is ag comhrá. Bhí a Daid an-bhuartha fúithi, mar ní raibh sí ag glacadh sosa nó ag fáil aer úr. Mhínigh a Mam gur cailín ciallmhar í agus go dtógann sí sos ag an deireadh seachtaine. Thuig a Mam go raibh sí ag staidéar go dian, ach nach raibh an iomarca brú uirthi.",
        "fifth":"Forbraíodh an scéal i bpictiúr a cúig. Tar eis cúpla mí, bhí Máire, a cairde agus a tuismitheoirí ag an scoil. Lá an dtorthaí a bhí ann, agus bhí neirbhís an domhain ar Mháire agus a tuismitheoirí. É sin ráite, thuig siad go raibh an obair agus staidéar déanta aici. Ar deireadh, d'oscail Máire na torthaí agus d'oibrigh sí amach a pointí. Bhí faoiseamh an domhain uirthi, mar fuair sí ceithre chéad caoga pointe. Bhí bród an domhain ar a tuismitheoirí, mar rinne sí a dícheall don bhliain.",
        "sixth":"Tagann imeachtaí chun deiridh sa phictiúr seo agus feicimid buaicphointe an scéil. Iontas na n-iontas, cúpla seachtaine ina dhiaidh, chuaigh Máire chuig Ollscoil na Gaillimhe. Is léir go raibh sí idir sceitimíneach agus neirbhíseach, ach bhí áthas an domhain uirthi a bheith ann. Bhí sí ag tnúth go mór le saol na hollscoile tar éis brú na hArdteiste. Mar a deir an seanfhocal \"aois na hóige, aois na glóire\". Ní dhéanfaidh sí dearmad ar an lá sin go deo." #type:ignore
    },
    "Comhoibriú":{
        "first":"Leagadh síos bunchloch an scéil sa chéad phictiúr. Lá dá raibh, bhí Úna agus Aoife ag spaisteoireacht sa bhaile beag. Thug siad faoi dheireadh go raibh an baile trí na chéile agus nár scuabadh an tsráid le fada. Bhí bruscar ar fud na háite agus bhí sé go hiomlán lofa. Bhí buidéal, páipéar agus pacáistí i ngach áit. Le bheith macánta, bhí náire ar an mbeirt acu. Dúirt Úna go raibh sé déistineach agus d'aontaigh Aoife go gcaifear feabhas a chur ar.",
        "second":"Bogadh an scéal ar aghaidh sa dara phictiúr. Socraíodh cruinniú ag Comhairle an Phobail chun réiteach na faidhbe a bhaint amach. D'fhreastail slua mór ar an gcruinniú seo agus d'éist siad go haireach leis na cailíní agus a gcúis imní. Chreid siad go léir go raibh an timpeallacht fíor-thábhachtach agus go mba chóir glantachán a chur ar siúl. Chuirfeadh sé le saol sóisialta na háite chomh maith. Bhunaigh siad coiste chun na feabhsaithe seo a chur i bhfeidhm thar ama. Thógfadh sé tamaill ach mar a deir an seanfhocal, tús maith, leath na hoibre.",
        "third":"Forbraíodh an scéal i bpictiúr a trí. Thosaigh an pobal ag glanadh an lá dár gcionn. Bailíodh an bruscar agus péinteáladh na ballaí. Anuas ar sin, baineadh na fiailí agus ba bheag go raibh an áit in ord 's in eagar arís. Glanadh an áit ó bhun go barr! D'fhág siad an phríomhshráid glan, néata agus slachtmhar. Bhain siad árd-taitneamh as a bheith ag obair le chéile 's ag glanadh. Ní neart go cur le chéile mar a deirtear.",
        "fourth":"Leantar leis an scéal sa chéad phictiúr eile. Chuaigh siad ag cabhrú le seanóirí chomh maith chun cabhrú le lucht na háite agus chun atmaisféar dearfach a chruthú. Bhí Aoife ag canadh agus ag baint taitneamh as an gceol. Bhí na seanóirí fíor-bhuíoch di faoi sin. Tháinig Garda chun labhairt leis an bpobal faoi shlándáil freisin agus go mba chóir don phobal a bheith ar aire.",
        "fifth":"Tá an pictiúr seo rointe i dtrí chuid. De réir dealraimh, tosaíodh ranganna oíche chomh maith. D'éirigh leo cócaireacht a chur ar siúl i rang amháin, gairneoireacht i rang eile agus bhí siad ag foghlaim faoi chúrsaí ríomhaireachta. Bhí an saol sóisialta ag dul i bhfeabhas sa bhaile.",
        "sixth":"Tagann imeachtaí chun deiridh sa phictiúr seo agus feicimid buaicphointe an scéil. Iontas na n-iontas, bhuaigh comhairle an phobail an baile beag leis an bhfeabhas is fearr. Ní raibh siad ag súil le duais ar bith. Ní haon ionadh go raibh siad mórálach as a gcuid oibre. Bronnadh seic orthu agus fuair siad dhá mhíle 's cúig chéad euro dá bharr. D'oibrigh siad le chéile agus b'fhiú é. Mar a deir an seanfhocal, de réir a chéile a thógtar na caisleáin. Ní dhéanfaidís dearmad ar an taithí sin go deo."
    } #type:ignore #type:ignore
} #type:ignore
#type:ignore
if __name__ == "__main__": #type:ignore
    import House #type:ignore