diction = { #type:ignore
    "Obair Dhian":{ #type:ignore
        "first":"Leagadh síos bunchloch an scéil sa chéad phictiúr. Lá dá raibh ag tús na séú bliana a bhí ann agus bhí na daltaí go léir ar ais ar scoil. Feicimid Máire ina suí in oifig an gairmthreoraí. Bhuail sí leis an ngairmthreoraí agus phléigh siad a roghanna don bhliain seo chugainn. Luaigh Máire go raibh suim aici sa cheimic sa Ghaillimh agus lorg sí eolas ón múinteoir. Mhínigh sé go raibh ceithre chéad pointe ag teastáil don chúrsa agus go mbeadh obair dhian ag teastáil.",
        "second":"Bogadh an scéal ar aghaidh sa dara phictiúr. An tráthnóna sin, bhuail Máire lena cara Síle agus shiúil siad abhaile le chéile.Labhair siad faoin lá agus faoi na ranganna a bhí acu. Feicimid buachaillí ag traenáil don chispheil sa chúlra. Thug Síle cuireadh do Mháire teacht chuig a teach do chupán tae, ach níor ghlac Máire leis an gcuireadh. Mhínigh sí go raibh a lán obair bhaile le déanamh aici.",
        "third":"Tá an pictiúr seo roinnte ina dhá leath. Lean an scéal ar aghaidh, agus níos déanaí an tráthnóna sin bhí Máire sa bhaile. Bhuail a fón póca agus d'fhreagair sí é. Ghlaoigh Seán uirthi agus thug sé cuireadh chuig an bpictiúrlann di. Dúirt sé léi go raibh scannán iontach sa phictiúrlann, ach arís eile dhiúltaigh Máire an cuireadh. Bhí aiste Béarla le scríobh aici an oíche sin.",
        "fourth":"Leantar leis an scéal sa chéad phictiúr eile. Feicimid Máire ina seomra leapa ag staidéar. Bhí sí ag obair go dian dícheallach agus bhí an iliomad leabhair timpeall uirthi. Bhí a tuismitheoirí sa chistin agus bhí siad ag caint is ag comhrá. Bhí a Daid an-bhuartha fúithi, mar ní raibh sí ag glacadh sosa nó ag fáil aer úr. Mhínigh a Mam gur cailín ciallmhar í agus go dtógann sí sos ag an deireadh seachtaine. Thuig a Mam go raibh sí ag staidéar go dian, ach nach raibh an iomarca brú uirthi.",
        "fifth":"Forbraíodh an scéal i bpictiúr a cúig. Tar eis cúpla mí, bhí Máire, a cairde agus a tuismitheoirí ag an scoil. Lá an dtorthaí a bhí ann, agus bhí neirbhís an domhain ar Mháire agus a tuismitheoirí. É sin ráite, thuig siad go raibh an obair agus staidéar déanta aici. Ar deireadh, d'oscail Máire na torthaí agus d'oibrigh sí amach a pointí. Bhí faoiseamh an domhain uirthi, mar fuair sí ceithre chéad caoga pointe. Bhí bród an domhain ar a tuismitheoirí, mar rinne sí a dícheall don bhliain.",
        "sixth":"Tagann imeachtaí chun deiridh sa phictiúr seo agus feicimid buaicphointe an scéil. Iontas na n-iontas, cúpla seachtaine ina dhiaidh, chuaigh Máire chuig Ollscoil na Gaillimhe. Is léir go raibh sí idir sceitimíneach agus neirbhíseach, ach bhí áthas an domhain uirthi a bheith ann. Bhí sí ag tnúth go mór le saol na hollscoile tar éis brú na hArdteiste. Mar a deir an seanfhocal \"aois na hóige, aois na glóire\". Ní dhéanfaidh sí dearmad ar an lá sin go deo." #type:ignore
    } #type:ignore #type:ignore
} #type:ignore
#type:ignore
if __name__ == "__main__": #type:ignore
    import House #type:ignore