sraiths = { #type:ignore
    "Lá Spraoi":{
        "first":"Leagadh síos bunchloch an scéil le scata daoine bailithe in Aerfort Átha Cliath. Bhí siad ina seasamh ag faire go géar ar na doirse isteach, mar bhí siad a feitheamh ar dhaoine éagsúla. Gan mhoill, shiúil cailín tríd an doras agus chuir Áine agus a máthair fáilte is fiche roimpi. Bhí gliondar croí orthu go léir agus mhínigh Áine an plean don turas.",
        "second":"Forbraíodh an scéal an mhaidin dar gcionn. Thóg na cailíní turas bus timpeall na cathrach chun na radhairc éagsúla a fheiceáil. Bhí treoraí ar an mbus, agus thug sí eolas iontach ar stair na háite. Thaispeáin sí na foirgnimh cáiliúla dóibh agus d'fhoghlaim gach duine an iliomad faoin gcathair. Shuigh na cailíní thuas staighre ar an mbus chun na suíomhanna a fheiceáil amuigh faoin aer. Bhí an t-ádh leo mar bhí aimsir mhaith acu don lá.",
        "third":"Le linn an turais bus, thug na cailíní cuairt ar áiteanna éagsúla. I dtosach báire, thug siad cuairt ar Choláiste na Tríonóide. Shiúil na cailíní timpeall na hollscoile agus d'fhéach siad ar an leabhar cheanannais. Bhí an-suim ag Áine ann, mar d'fhoghlaim sí faoi ar scoil sa rang staire. Bhí siad an-tógtha le hatmaisféar na háite agus bhí siad ag brionglóid faoi na laethanta ollscoile rompu sa todhchaí. Bhí siad in éad leis na mic léinn ollscoile agus iad ag siúl timpeall.",
        "fourth":"Tar éis uair a chloig, d'fhill na cailíní ar an mbus agus thug siad cuairt ar shuíomhanna eile. Rinne siad turas i bPáirc an Chrócaigh chomh maith le cuairt chuig an músaem. Shiúil siad timpeall gairdín na nainmhithe agus ghlac siad grianghraif ann. Thiomáin an bus thart ar an staid Aviva ach níor stop sé ann. Ar deireadh, thug siad cuairt ar Ardeaglais Naomh Pádraig.",
        "fifth":"Tar éis lá fada turasóireachta, bhí na cailíní tuirseach traochta agus stiúctha leis an ocras. Bheartaigh siad bia a fháil i mbialann beag ar chúinne Shráid Ghrafton. Bhí atmaisféar deas ann leis na siopadóirí timpeall na háite agus shuigh siad lasmuigh ar an sráid. D'ordaigh siad plátaí beaga agus roinn siad iad eatarthu. Bhí béile blasta acu agus bhí an bia úr agus folláin. Chríochnaigh siad an béile le cupán caifé.",
        "sixth":"Ar a leathuair tar éis a seacht, shiúil na cailíní chomh fada le hAmharclann na Mainistreach, mar bhí ticéid acu don dráma 'The Field' ann. Bhí tuairiscí iontacha léite acu ar líne agus bhí an t-ádh dearg leo na ticéid a fháil. Thaitin an dráma go mór leo, agus d'aontaigh siad go raibh na gradaim tuilte go mór ag na haisteoirí. Is léir gur bhain na cailíní idir thaitneamh agus tairbhe as a lá san ardchathair."
    },
    "Rialacha":{
        "first":"Leagadh síos bunchloch an scéil sa chéad phictiúr. Lá dá raibh, labhair príomhoide Ardscoil an Chnoic leis na daltaí ag an tionóil. Luaigh sí rialacha na scoile. Dar leis na rialacha, ba chóir go mbeadh meas acu ar chách, éide scoile a chaitheamh agus mar sin de. Chuir sí béim ar chosc ar an mbulaíocht agus tobac a chaitheamh chomh maith. Thug sí foláireamh dóibh nach nglacfaidís le briseadh rialacha.",
        "second":"Bogadh an scéal ar aghaidh sa dara phictiúr. Is beag aird a thug Liam agus Úna ar na rialacha. Sa chlós, bhí Liam ag troid le buachaill eile. Bhí raic cheart ann. Chomh maith leis sin, bhí Máire ag caitheamh tobac le cailín eile. Ba chuma sa sioc leo faoi na rialacha. Tháinig na múinteoirí orthu agus déarfainn go raibh siad i bponc ceart. Ní raibh tús maith acu.",
        "third":"Tá an pictiúr seo roinnte i ndá leath. Rug na múinteoirí orthu beirt agus bhí siad i dtrioblóid. Liostaigh na múinteoirí na rialacha a bhris siad agus cheistigh siad an bheirt acu agus na daoine eile a bhí bainteach leis. Bhí díomá ar na múinteoirí. Mhínigh siad gur cur amú airgid é caitheamh tobac agus go ndéanann sé dochar do na scamhóga agus don sláinte ghinearálta. Mar a deireann an seanfhocal, is fearr an tsláinte ná na táinte.",
        "fourth":"Forbraíodh ar an scéal i bpictiúr a cheathair agus níorbh shin deireadh leis. Ghlaoigh an príomhoide a dtuismitheoirí agus bhí orthu teacht isteach an mhaidin dár gcionn. Bhí a dtuismitheoirí ar buile leo agus tugadh íde na muc is na madraí dóibh. Bhí Liam agus Úna go hiomlán in umar na haimléise. Mar a deirtear, filleann an feall ar an bhfeallaire.",
        "fifth":"Leanadh leis an scéal sa chéad phictiúr eile. Bhuail na tuismitheoirí leis an bpríomhoide agus mhínigh sí gur sháraigh na daltaí rialacha na scoile. Bhí ar na tuismitheoirí agus na daltaí fanacht sa seomra feithimh go dtí gur ghlaoigh an príomhoide isteach iad. Bhí atmaisféar teannasach sa seomra agus ní raibh aon duine ar a gcompórd ann. Bhí Liam agus Úna ag crith agus bhí náire ar na tuismitheoirí.",
        "sixth":"Tagann imeachtaí chun deiridh sa phictiúr seo. Faoi dheireadh, bhí orthu fanacht tar éis scoile. Bhí ar Úna fanacht isteach ar feadh uair an chloig agus bhí ar Liam fanacht ann ar feadh dhá uair. Bhí an seomra chomh ciúin le reilig agus is léir go raibh leadrán an domhain orthu. Bhí ceacht luachmhar foghlama acu. Mar a deirtear, ní thagann ciall roimh aois agus is fíor sin. Ní dhéanfaidís dearmad ar an lá sin go deo."
    },
    "Mo Cheol Thú":{
        "first":"Leagadh síos bunchloch an scéil sa chéad phictiúr. Lá dá raibh, bhí grúpa traidisiúnta i gColáiste Phádraig. Bhí siad ag cleachtadh ceoil ag am lóin agus tar éis scoile gach Luain agus Céadaoin. Bhain siad an-taitneamh as a bheith ag seinm ceoil le chéile. Mar a mheabhraíonn an seanfhocal, 'cleachtadh a dhéanann máistreacht'.",
        "second":"Bogadh an scéal ar aghaidh sa dara phictiúr. Chleachtaigh an dream go rialta agus tháinig feabhas orthu diaidh ar ndiaidh. Bhí feadóg mhór, feadóg stáin agus dhá fhidil á seinnt acu. Bhí siad go léir sásta leis an bhfuaim. Bhí an múinteoir ceoil, an Mháistir Ó Tuama ag éisteacht leo agus é ag tabhairt aiseolais cruinn dóibh. Deirtear go bhfuil bua sa cheol ag an Máistir.",
        "third":"Forbraíodh an scéal i bpictiúr a trí. Bhí port nua le hullmhú acu mar obair bhaile gach seisiún. Lean siad orthu cé go raibh sé deacair. Is léir go raibh dúil sa cheol ag cailín darb ainm Úna agus í ag cleachtadh seacht lá na seachtaine.",
        "fourth":"Leantar leis an scéal sa chéad phictiúr eile. De réir dealraimh, chuaigh an grúpa ceoil isteach ar Fhleá an Chontae, tar éis na míonna ag seinm. Bhí ceithre ghrúpa sa chomórtas ach iontas na n-iontas, bhuaigh siad an chéad áit! D'éirigh leo i bhFleá an Chúige chomh maith agus rug siad an chraobh ansin. Ní féidir a shéanadh ach go raibh siad ar bís agus an-sásta leo féin",
        "fifth":"Tá an pictiúr seo rointe ina dhá leath. Faoi dheireadh, chuaigh siad go Fleá Cheoil na hÉireann i Litir Ceanainn. Nuair a shroich siad an Fleá, thug siad faoi dheireadh go raibh an-chuid grupaí. Bhí an iomaíocht an-ghéar agus bhí atmaisféar teannasach le brath. Níorbh ionadh gur bhuaigh Coláiste Phádraig an chéad áit. Sheinn siad arís ag ceolchoirm na mbuaiteoirí agus bhí an-chéiliúradh an oíche sin. Bhí siad fíor-mhóralach as a gcuid iarrachtaí.",
        "sixth":"Tagann imeachtaí chun deiridh sa phictiúr seo agus feicimid buaicphointe an scéil. Bhí céiliúradh freisin dóibh i gColáiste Phádraig. Sheinn siad an oíche sin do dhaltaí agus do mhúinteoirí na scoile. Threaslaigh an príomhoide leo agus leis na múinteoirí agus leis na tuismitheoirí a chuidigh leo. Bua stairiúil ba ea é. Ní dhéanfaidís dearmad ar an taithí sin go deo."
    },
    "An Ghaeilge":{
        "first":"Leagadh síos bunchloch an scéil i bpictiúr a haon, nuair a bhí Åine agus Seán ina seasamh taobh amuigh den siopa ceoil. Bhí sladmhargadh na Cásca ar siúl agus bhí rudaí níos saoire sa siopa. Feicimid uirlisí ceoil san fhuinneog, mar shampla bosca ceoil, bodhrán, cláirseach, agus bainseó. Bhí comharthaí Gaeilge ar an doras. Labhair an bheirt acu faoin nGaeilge, agus ní féidir a shéanadh ach go raibh siad sásta go raibh an Ghaeilge in úsáid sa siopa. Dúirt Seán gur chóir dóibh an Ghaeilge a chur chun cinn agus bhí Aine ar aon intinn leis, ar ndóigh.",
        "second":"Chuaigh siad abhaile, agus chas siad an ríomhaire ar siúl. Bhí siad ar an idirlíon ar an ríomhaire. D' fhéach siad ar Facebook, agus chuardaigh siad eolas ar thuras chun na Gaeltachta. Phléigh siad na buntáistí a bhaineann le turas Gaeltachta. Chreid an bheirt acu go mbeadh sé fiúntach cúrsa Gaeilge a dhéanamh ann. Ar deireadh, bheartaigh siad dul ann ar thuras, agus lorg siad cead óna dtuismitheoirí.",
        "third":"Cúpla mí ina dhiaidh, thaistil na daltaí chuig an nGaeltacht agus feicimid iad ann. Sa chéad phíosa, bhí Åine, Seán agus Pól ag déanamh comhrá. Phléigh siad rudaí éagsúla trí Ghaeilge. Sa dara píosa, bhí siad sa halla áitiúil ag glacadh páirte i gcéilí. Bhí siad ag rince agus sheinn ceoltóiri ceol traidisiúnta. I bpíosa a trí, d'imir siad cluiche eitpheile ar an trá. Bhí an ghrian ag spalpadh anuas. Bhi siad sona sásta agus bhain siad taitneamh as. Is léir go raibh na déagóirí go léir ag baint a lán taitnimh as a dturas Gaeltachta agus ag déanamh iarrachta an teanga a úsáid.",
        "fourth":"I Mi Mheán Fómhair, d'fhill na daltaí ar scoil tar éis an tSamhraidh. Bhi éadaí scoile ar na daltaí go léir. Bheartiagh siad leanúint lena ndul chun cinn ón nGaeltacht agus bheartaigh siad an Ghaeilge a úsáid níos minice i rith na scoilbhliana. Am lóin a bhí ann, agus ghlac siad páirte i gciorcal cainte. Bhí na daltaí go léir ag déanamh comhrá. Phléigh siad rudaí éagsúla, agus tháinig feabhas ar a leibhéal cainte.",
        "fifth":"Chomh maith 1leis an gciorcal comhrá, rinne siad cinneadh leas a bhaint as na stáisiúin náisiúnta. Gach Déardaoin, d'éist Aine le clár faisean ar Raidió na Gaeltachta ar an iPod. Bhí cluasáin ina cluasa aici. Sa dara leath, shuigh Aine agus Seán sa seomra suite. D'fhéach siad ar an teilifis ar TG4. Bhí siad ag féachaint ar chlár reatha. Duirt Áine gur fiú féachaint ar TG4. Thuig sí gur chabhraigh sé lena foghlaim agus thug an feabhas ar a tuiscint misneach di.",
        "sixth":"Ag deireadh na bliana, bhí Oíche Gradam ar scoil. Ní haon ionadh é go bhfuair na daltaí gradam, mar chuir siad an Ghaeilge chun cinn ar scoil agus sa cheantar. Bhií áthas an domhain orthu agus mhothaigh siad an-bhródúil. Bhronn an príomhoide duais orthu agus ghlac siad leis an duais. Mhol sí na daltaí don iarracht. Is léir gur bhain na daltaí idir taitneamh agus tairbhe as an nGaeilge a chur chun cinn."
    },
    "An Fhoireann":{
        "first":"Leagadh síos bunchloch an scéil sa chéad phictiúr. An chéad Luain de mhí Mheán Fómhair, agus ar ndóigh, an chéad lá scoile tar éis an tSamhraidh a bhí ann. Bhí Seán agus Eoghan ag caint is ag comhrá taobh amuigh den oifig spóirt agus thóg siad fógra don sraith iomána faoi deara. Phléigh na buachaillí an fógra agus dúirt Seán go raibh sé spéisiúil agus go mbainfeadh sé triail as. Dúirt Eoghan go labhródh sé leis an Uasal Ó Riain chun tuilleadh eolais a fháil uaidh.",
        "second":"Tá an pictiúr seo rointe ina dhá leath. Lean an scéal ar aghaidh sa phictiúr seo agus níos déanaí sa tseachtain feicimid na buachaillí ag plé cúrsaí iomána. Chuir Seán ceist ar Eoghan an raibh suim aige ann agus d'fhreagair Eoghan go mbainfidís triail as. Gan mhoill chuaigh siad ar thóir ar Uasal Ó Riain agus léirigh siad a suim. Cheistigh siad an traenálaí chun na sonraí a fháil. Mhínigh sé go mbeadh traenáil dhá lá tar éis scoile riachtanach.",
        "third":"Forbraíodh an scéal i bpictiúr a trí nuair a fheicimid na daltaí ar an bpáirc imeartha agus seisiún traenála faoi lán seoil. D'fhéach an bainisteoir go géar orthu ag traenáil agus thug sé comhairle dóibh. Rinne na buachaillí obair na gcapall i ngach seisiún traenála, agus bhí iomaíocht iontach eatarthu. D'oibrigh siad go dian agus tháinig feabhas ar a scileanna lá i ndiaidh lae.",
        "fourth":"Leantar leis an scéal sa chéad phictiúr eile. Tar éis na míonna fada traenála, feicimid gur fiú go mór é nuair a mhínigh an bainisteoir na foirne go raibh siad sa chraobh. Bhí cruinniú foirne agus phléigh siad an craobh. Líon an bainisteoir an fhoireann le spiorad agus misneach lena óráid ionsparáideach. Eagraíodh busanna chuig an gcluiche don lucht tacaíochta agus bhí fógraí ar fud na scoile. Chláraigh slua mór do na busanna chun tacaíocht a thabhairt don fhoireann.",
        "fifth":"Bogadh an scéal ar aghaidh i bpictiúr a cúig. De réir dealraimh, shroich lá an chluiche. Bhí an staid líon lán leis an lucht tacaíochta agus bhí atmaisféar leictreach sa staid. Bhí na himreoirí idir neirbhíseach agus sceitimíneach. Tar éis cluiche den chéad scoth, bhuaigh Coláiste Eoin. Bronnadh an corn orthu agus bhí gliondar croí agus faoiseamh orthu. Cluiche teannasach é, ach bhí an bua tuilte acu ar deireadh.",
        "sixth":"Tagann imeachtaí chun deiridh sa phictiúr seo agus feicimid buaicphointe an scéil. An mhaidin i ndiaidh an chluiche, bhí an fhoireann ar ais ar scoil. Bhuail an príomhoide agus bainisteoir leis na himreoirí. Labhair an príomhoide leo agus mhol sé go hard na spéire iad. Is léir go raibh muintir na scoile an-bhródúil as éacht na mbuachaillí. Luaigh an príomhoide go n-eagródh sé cóisir mar chéiliúradh agus bhí na buachaillí ag súil leis an ócáid. Is cinnte gur bhain na buachaillí idir thaitneamh agus tairbhe as an mbliain leis an bhfoireann iománaíochta. Ní dhéanfidís dearmad ar an taithí sin go deo."
    },
    "Obair Dhian":{ #type:ignore
        "first":"Leagadh síos bunchloch an scéil sa chéad phictiúr. Lá dá raibh ag tús na séú bliana a bhí ann agus bhí na daltaí go léir ar ais ar scoil. Feicimid Máire ina suí in oifig an gairmthreoraí. Bhuail sí leis an ngairmthreoraí agus phléigh siad a roghanna don bhliain seo chugainn. Luaigh Máire go raibh suim aici sa cheimic sa Ghaillimh agus lorg sí eolas ón múinteoir. Mhínigh sé go raibh ceithre chéad pointe ag teastáil don chúrsa agus go mbeadh obair dhian ag teastáil.",
        "second":"Bogadh an scéal ar aghaidh sa dara phictiúr. An tráthnóna sin, bhuail Máire lena cara Síle agus shiúil siad abhaile le chéile.Labhair siad faoin lá agus faoi na ranganna a bhí acu. Feicimid buachaillí ag traenáil don chispheil sa chúlra. Thug Síle cuireadh do Mháire teacht chuig a teach do chupán tae, ach níor ghlac Máire leis an gcuireadh. Mhínigh sí go raibh a lán obair bhaile le déanamh aici.",
        "third":"Tá an pictiúr seo roinnte ina dhá leath. Lean an scéal ar aghaidh, agus níos déanaí an tráthnóna sin bhí Máire sa bhaile. Bhuail a fón póca agus d'fhreagair sí é. Ghlaoigh Seán uirthi agus thug sé cuireadh chuig an bpictiúrlann di. Dúirt sé léi go raibh scannán iontach sa phictiúrlann, ach arís eile dhiúltaigh Máire an cuireadh. Bhí aiste Béarla le scríobh aici an oíche sin.",
        "fourth":"Leantar leis an scéal sa chéad phictiúr eile. Feicimid Máire ina seomra leapa ag staidéar. Bhí sí ag obair go dian dícheallach agus bhí an iliomad leabhair timpeall uirthi. Bhí a tuismitheoirí sa chistin agus bhí siad ag caint is ag comhrá. Bhí a Daid an-bhuartha fúithi, mar ní raibh sí ag glacadh sosa nó ag fáil aer úr. Mhínigh a Mam gur cailín ciallmhar í agus go dtógann sí sos ag an deireadh seachtaine. Thuig a Mam go raibh sí ag staidéar go dian, ach nach raibh an iomarca brú uirthi.",
        "fifth":"Forbraíodh an scéal i bpictiúr a cúig. Tar eis cúpla mí, bhí Máire, a cairde agus a tuismitheoirí ag an scoil. Lá an dtorthaí a bhí ann, agus bhí neirbhís an domhain ar Mháire agus a tuismitheoirí. É sin ráite, thuig siad go raibh an obair agus staidéar déanta aici. Ar deireadh, d'oscail Máire na torthaí agus d'oibrigh sí amach a pointí. Bhí faoiseamh an domhain uirthi, mar fuair sí ceithre chéad caoga pointe. Bhí bród an domhain ar a tuismitheoirí, mar rinne sí a dícheall don bhliain.",
        "sixth":"Tagann imeachtaí chun deiridh sa phictiúr seo agus feicimid buaicphointe an scéil. Iontas na n-iontas, cúpla seachtaine ina dhiaidh, chuaigh Máire chuig Ollscoil na Gaillimhe. Is léir go raibh sí idir sceitimíneach agus neirbhíseach, ach bhí áthas an domhain uirthi a bheith ann. Bhí sí ag tnúth go mór le saol na hollscoile tar éis brú na hArdteiste. Mar a deir an seanfhocal 'aois na hóige, aois na glóire'. Ní dhéanfaidh sí dearmad ar an lá sin go deo." #type:ignore
    },
    "Timpiste":{
        "first":"Leagadh síos bunchloch an scéil sa chéad phictiúr. Lá dá raibh, an samhradh a bhí ann. Chríochnaigh an scoil agus bhí Pól, Tomás agus Seán nach mór ag déanamh na hArdteiste. Socraítear go rachfaidís go dtí an Ghaeltacht chun a scileanna labhartha a fheabhsú toisc go raibh béim ollmhór ar an scrúdú cainte - beatha teanga, í a labhairt mar a deirtear. Mar sin, d'fhreastail siad ar chúrsa Gaeilge i gConamara. Thug a dtuismitheoirí síob dóibh go dtí an Ghaeltacht agus bhí sceitimíní orthu. D'fhág siad slán leo agus bhuail siad an bóthar. Bhí siad an-luath agus ní raibh duine ná deoraí thart.",
        "second":"Bogadh an scéal ar aghaidh sa dara phictiúr. Crochadh clár ama an chúrsa ar an mballa. Reáchtáladh go leor imeachtaí éagsúla. Bhíodh ranganna ar siúl ar maidin, spórt san iarnóin agus céilí nó seó tallainne istoíche. Ní raibh aon dá lá mar a chéile. Is cinnte go mbeidís tuirseach, traochta, tnáite gach oíche.",
        "third":"Forbraíodh an scéal i bpictiúr a trí. Lá amháin bhí cluiche peile faoi lán seoil. Bhí an triúir acu ar fhoirne difriúla agus ba léir go raibh iomaíocht an-ghéar eatarthu. Bhí greim an duine bháite ag Pól ar an liathróid agus é ag rith ar luas lasrach. I bpreabadh na súl bhí sé leagtha chun na talún. Thosaigh sé ag béicíl in ard a chinn is a ghutha. Ba bheag nár thit sé i laige leis an bpian agus bhí gach duine ag stánadh air le heagla.",
        "fourth":"Leantar leis an scéal sa chéad phictiúr eile. Thug an múinteoir lámh chúnta do Phól dul isteach sa charr. Mhothaigh Tomás an-trua do Phól mar go raibh an t-ospidéal caoga míle ar shiúl uathu. Ina theannta sin tá an-dúil ag Pól sa spórt agus ba léir nach mbeadh sé in ann imirt le tamaill. D'iarr an príomhoide ar an múinteoir glaoch air ón ospidéal chun iad a chur ar an eolas go mbeidís ag teacht. Bhí crith cos agus lámh ar Phól bocht.",
        "fifth":"Tá an pictiúr seo rointe i ndá chuid. De réir dealraimh, shroich siad an t-ospidéal tuairim is uair an chloig ina dhiaidh sin. Rinne an dochtúir sa seomra éigeandála scrúdú ar chos Phóil. Bhí dea-scéal aige dó. Ní raibh a chos briste. Bheadh Pól i mbarr a mhaitheasa arís i gceann seachtaine. Lig an múinteoir agus Pól osna faoisimh nuair a chuala siad an scéal seo. Cuireadh glaoch ar thuismitheoirí Phóil leis an dea-scéal a insint dóibh.",
        "sixth":"Tagann imeachtaí chun deiridh sa phictiúr seo agus feicimid buaicphointe an scéil. Iontas na n-iontas, d'fhill siad ar an gcoláiste samhraidh ina dhiaidh sin. Bhí áthas an domhain ar chairde Phóil é a fheiceáil. Chuir siad fáilte chroíúil roimhe. Bhí meangadh mór gáire ar Phól arís. Ní bheadh sé in ann rince ag an gcéilí agus bhí díomá air faoi sin. B'fhéidir go mbeadh sé in ann díriú ar a chuid Gaeilge mar thoradh! Mar a deir an seanfhocail, cleachtadh a dhéanann máisteacht. Ní dhéanfaidís dearmad ar an lá sin go deo."
    },
    "Comhoibriú":{
        "first":"Leagadh síos bunchloch an scéil sa chéad phictiúr. Lá dá raibh, bhí Úna agus Aoife ag spaisteoireacht sa bhaile beag. Thug siad faoi dheireadh go raibh an baile trí na chéile agus nár scuabadh an tsráid le fada. Bhí bruscar ar fud na háite agus bhí sé go hiomlán lofa. Bhí buidéal, páipéar agus pacáistí i ngach áit. Le bheith macánta, bhí náire ar an mbeirt acu. Dúirt Úna go raibh sé déistineach agus d'aontaigh Aoife go gcaifear feabhas a chur ar.",
        "second":"Bogadh an scéal ar aghaidh sa dara phictiúr. Socraíodh cruinniú ag Comhairle an Phobail chun réiteach na faidhbe a bhaint amach. D'fhreastail slua mór ar an gcruinniú seo agus d'éist siad go haireach leis na cailíní agus a gcúis imní. Chreid siad go léir go raibh an timpeallacht fíor-thábhachtach agus go mba chóir glantachán a chur ar siúl. Chuirfeadh sé le saol sóisialta na háite chomh maith. Bhunaigh siad coiste chun na feabhsaithe seo a chur i bhfeidhm thar ama. Thógfadh sé tamaill ach mar a deir an seanfhocal, tús maith, leath na hoibre.",
        "third":"Forbraíodh an scéal i bpictiúr a trí. Thosaigh an pobal ag glanadh an lá dár gcionn. Bailíodh an bruscar agus péinteáladh na ballaí. Anuas ar sin, baineadh na fiailí agus ba bheag go raibh an áit in ord 's in eagar arís. Glanadh an áit ó bhun go barr! D'fhág siad an phríomhshráid glan, néata agus slachtmhar. Bhain siad árd-taitneamh as a bheith ag obair le chéile 's ag glanadh. Ní neart go cur le chéile mar a deirtear.",
        "fourth":"Leantar leis an scéal sa chéad phictiúr eile. Chuaigh siad ag cabhrú le seanóirí chomh maith chun cabhrú le lucht na háite agus chun atmaisféar dearfach a chruthú. Bhí Aoife ag canadh agus ag baint taitneamh as an gceol. Bhí na seanóirí fíor-bhuíoch di faoi sin. Tháinig Garda chun labhairt leis an bpobal faoi shlándáil freisin agus go mba chóir don phobal a bheith ar aire.",
        "fifth":"Tá an pictiúr seo roinnte i dtrí chuid. De réir dealraimh, tosaíodh ranganna oíche chomh maith. D'éirigh leo cócaireacht a chur ar siúl i rang amháin, gairneoireacht i rang eile agus bhí siad ag foghlaim faoi chúrsaí ríomhaireachta. Bhí an saol sóisialta ag dul i bhfeabhas sa bhaile.",
        "sixth":"Tagann imeachtaí chun deiridh sa phictiúr seo agus feicimid buaicphointe an scéil. Iontas na n-iontas, bhuaigh Comhairle an Phobail an baile beag leis an bhfeabhas is fearr. Ní raibh siad ag súil le duais ar bith. Ní haon ionadh go raibh siad mórálach as a gcuid oibre. Bronnadh seic orthu agus fuair siad dhá mhíle 's cúig chéad euro dá bharr. D'oibrigh siad le chéile agus b'fhiú é. Mar a deir an seanfhocal, de réir a chéile a thógtar na caisleáin. Ní dhéanfaidís dearmad ar an taithí sin go deo."
    },
    "Breoite":{
        "first":"Leagadh síos bunchloch an scéil sa chéad phictiúr. Lá dá raibh, chuaigh Síle agus Úna amach i gcomhair na hoíche. Mar a tharlaíonn sé, bhí breithlá Úna á cheiliúradh acu. Chuaigh siad go club oíche agus bhí oíche den scoth acu. Ina dhiaidh sin, chuaigh siad ag ithe mar bhí ocras an domhain orthu ag deireadh na hoíche. Bhí siad ag baint súp as an oíche agus ní raibh cíos, cás ná cathú orthu.",
        "second":"Bogadh an scéal ar aghaidh sa dara phictiúr. An mhaidin dár gcionn, bhuail clog Úna ag a seacht a chlog. Baineadh geit aisti. Bhí sí tuirseach, traochta, tnáite agus ní raibh fonn uirthi éirí. Bhí aiféala uirthi go ndeachaigh sí amach agus bhí sí i bponc ceart. D'éirigh Úna go mall. Dúirt sí lena Mam go raibh sí lag agus traochta. Thuig sí láithreach go mbeadh lá fhada aici. D'fhanfadh sí sa leaba dá raibh rogha aici.",
        "third":"Forbraíodh an scéal i bpictiúr a trí agus d'ullmhaigh sí í féin don scoil. Ní raibh aon trua ag a máthair di agus dúirt sí le hÚna go gcaithfeadh sí dul ar scoil. Ba léir go raibh Úna in umar na haimsléise ach ní raibh an dara rogha aici. Thug sí aghaidh ar stad an bhus go drogallach. Bhí sé ag stealladh báistí agus bhí sé fuar agus fliuch agus í ag feitheamh don bhus. Mar a mheabhraíonn an seanfhocal, filleann an feall ar an bhfeallaire.",
        "fourth":"Leantar leis an scéal sa chéad phictiúr eile. Bhí sí fliuch go craiceann  nuair a shroich sí an scoil. Creid é nó ná creid, bhí dearmad glan déanta aici ar an scrúdú Tíreolais agus níor ullmhaigh sí. Mhothaigh sí an-tinn. Bhí tinneas cinn nimhneach uirthi agus ní raibh sí ábalta díriú ar an scrúdú.",
        "fifth":"Tá an pictiúr seo roinnte i ndá leath. Shroich sí deireadh na feide tar éis fiche nóiméad. Bhí fonn múisce ag teacht uirthi agus d'iarr sí ar an múinteoir an bhféadfadh sí dul amach. Theastaigh uaithi dul abhaile chomh luath agus ab fhéidir. Chuaigh sí go hoifig an phríomhoide le cead a lorg glaoch abhaile.",
        "sixth":"Tagann imeachtaí chun deiridh sa phictiúr seo agus feicimid buaicphointe an scéil. Bhí an príomhoide chomh buartha sin faoi Úna gur chuir sí fios ar an dochtúir. Rinne an dochtúir í a scrúdú go mion. Bhí sé den tuairim go bhfuair sí nimhiú bia. Moladh do Shíle imeacht abhaile agus a scíth a ligean. Dúirt an dochtúir go dtiocfadh sí chuici féin laistigh de chúpla lá. Ní dhéanfaidh sí dearmad ar an lá sin go deo."
    },
    #"Thig":{ #type:ignore
        #"Réamhrá":"Aontaím go huile is go hiomlán leis an ráiteas thuas. Is dírbheathaisnéis an leabhar seo ina insítear dúinn scéal bheatha an scríobhneora. Dar liom féin, is scéalaí den chéadscoth an t-údar. Tá ar a chumas craiceann a chur ar scéal, fiú nuair a shamhlaítear don léitheoir go bhfuil na heachtraí pas beag áiféiseach. Is dírbheathaisnéis dáiríre é seo ina nochtann an scríobhneor imeachtaí a shaoil agus saol daoine eile. Níl dabht ar bith ach an chuid is spéisiúla den leabhar seo ná an léiriú a thugann Maidhc Dainín ar laethanta a óige sa ghaeltacht. San aiste seo, pléifidh mé:",
        #"Cluiche Peile":"D'ainneoin go raibh cúrsaí eacnamaíochta, cúrsaí fostaíochta agus cúrsaí sóisialta go mór ar an gcúl sna caogaidí, níor chuir an méid seo isteach ar an dtaitneamh a bhain Maidhc Dainín as a óige. D'fhreastail Maidhc Dainín ar scoil Bhaile an Mhúraigh agus bhíodh sé de nós ag na scoláirí leasainmneacha a thabhairt ar a chéile. Tugadh 'Siúit' mar leasainm ar Mhaidhc. D'imir na buachaillí cluiche peile ar an mbóthar mar ní raibh trácht ag an am úd. Cluiche gan mórán ríalacha a bhí ann. Tá sé sóiléir ó na heachtraí seo gur mhaith leis na laethanta sa scoil Bhaile an Mhúraigh. Bhí slua mór ag imirt agus bhí scór féin ag gach duine. Cluiche garbh a bhía ann agus nuair a fuair duine an liathróid, níorbh fhada go raibh fiche duine timpeall orthu.",
        #"Róbheag":"Fiú agus Maidhc ag insint faoin gcéad lá ar scoil-ní raibh a fhios aige go raibh sé ag dul ar scoil. Níor thuig sé cén fáth a nigh a mháthair é. Ní raibh a fhios aige cén fáth a raibh sé gléasta suas go deas néata mar níorbh an Domhnach a bhí ann! Cheap sé féin go raibh sé ag dul chuig an siopa mar bhí sé 'róbheag chun dul ar scoil' dar leis.",
        #"Scaradh":"Insíonn Maidhc Dainín faoi na cluichí caide a bhíodh ag na buachaillí i gclós na bunscoile. Ní bhíodh réiteoir ar bith acu. Muna mbeadh duine tapa go leor ag scaradh leis an liathróid bheadh fiche duine bailithe timpeall air de gheit. Bhíodh na buachaillí ag iarraidh breith ar an liathróid. Níor bhain ríalacha leis na cluichí seo agus baineadh úsáid as clocha chun an cúl a mharcáil.",
        #"An Troid":"Scéal greannmhar a insíonn MD dúinn ná an cur síos a thugann sé ar an troid idir é féin agus an buachaill ó Chathair Scoilbín. Chaith an bheirt acu seachtain ag tabhairt íde béil dá chéile sula raibh troid ann. Ar deireadh thiar thall, thosaigh troid lá ag am lóin. Níorbh fhada go raibh slua bailithe timpeall orthu, mar ba chuid riachtanach de shaol na scoile í an troid, dar leis an údar. Bhí buachaill eile ann agus bhuail sé an bheirt acu, ag iarraidh iad a chur as. Shíl MD gurbh é an buachaill ó Chathair Scoilbín. Bhuail sé sa chluas é agus leagadh ar an talamh é. Níorbh fhada eile go raibh MD ar an talamh agus gur tháinig an múinteoir amach. Chaill sí an ceann ar fad agus thug sí trí stiall den fhuinseoig an duine dóibh. Insíonn MD an scéal seo i slí fíor-thaitneamhach, cinnte.",
        #"Troid":"Shíl MD gurbh é an buachaill ó Chathair Scoilbín. Bhuail sé sa chluas é agus leagadh ar an talamh é. Níorbh fhada eile go raibh MD ar an talamh agus gur tháinig an múinteoir amach. Chaill sí an ceann ar fad agus thug sí trí stiall den fhuinseoig an duine dóibh. Insíonn MD an scéal seo i slí fíor-thaitneamhach, cinnte."
    #} #type:ignore #type:ignore
} #type:ignore
#type:ignore
if __name__ == "__main__": #type:ignore
    import House #type:ignore